### ISSUE TITLE
Failed to discover OP endpoint URL

### ISSUE THREAD

**Issue by yangdezuan** [liamcurry/passport-steam#123]
Listening, port 80
InternalOpenIDError: Failed to discover OP endpoint URL
    at H:\wanmeiweb\web\git_oschina\servers\signsteam\node_modules\@passport-next\passport-openid\lib\passport-openid\strategy.js:249:52
    at H:\wanmeiweb\web\git_oschina\servers\signsteam\node_modules\openid\openid.js:757:14
    at H:\wanmeiweb\web\git_oschina\servers\signsteam\node_modules\openid\openid.js:547:13
    at H:\wanmeiweb\web\git_oschina\servers\signsteam\node_modules\openid\openid.js:503:11
    at H:\wanmeiweb\web\git_oschina\servers\signsteam\node_modules\openid\http.js:41:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
help!  Thanks

**Comment by yangdezuan** [comment]
Fixed by myself. Due to  local host bind
