### ISSUE TITLE
Failed to discover OP endpoint URL

### ISSUE THREAD

**Issue by maruo34** [liamcurry/passport-steam#126]
Failed to discover OP endpoint URL" 

Why is this happening? 

"passport-steam": "^1.0.18"

InternalOpenIDError: Failed to discover OP endpoint URL
    at /var/www/node_modules/@passport-next/passport-openid/lib/passport-openid/strategy.js:249:52
    at /var/www/node_modules/openid/openid.js:757:14
    at /var/www/node_modules/openid/openid.js:547:13
    at /var/www/node_modules/openid/openid.js:503:11
    at /var/www/node_modules/openid/http.js:41:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  openidError: { message: 'No providers found for the given identifier' }
}

**Comment by maruo34** [comment]
Steam dropped as always)
