### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by pronebird** [liamcurry/passport-steam#16]
Not quite sure why it happens.

```
/Users/username/project/node_modules/passport-steam/lib/passport-steam/strategy.js:62
            _json: result.response.players[0],
                         ^
TypeError: Cannot read property 'response' of undefined
  at steam.getPlayerSummaries.callback (/Users/username/project/node_modules/passport-steam/lib/passport-steam/strategy.js:62:26)
  at ClientRequest.<anonymous> (/Users/username/project/node_modules/passport-steam/node_modules/steam-web/lib/steam.js:257:5)
  at ClientRequest.emit (events.js:107:17)
  at Socket.socketErrorListener (_http_client.js:272:9)
  at Socket.emit (events.js:107:17)
  at net.js:451:14
  at process._tickDomainCallback (node.js:381:11)
```

**Comment by Zonalhaz** [comment]
I've had this issue too. It works fine on localhost but crashes randomly on heroku.

**Comment by men232** [comment]
Hey, i fixed it in by fork :)
https://github.com/men232/passport-steam

**Comment by ShaZZamHP** [comment]
Hi, I have the same problem so far

**Comment by DPr00f** [comment]
hey @men232,
Since you've fixed, couldn't you make a pull request to this library so it would be fixed in the original repo?

**Comment by looterz** [comment]
It seems like this repo is unsupported now, it might be worth creating a fork and fixing up some of the outstanding issues. Unfortunately this is the only passport authentication module for steam.

**Comment by DPr00f** [comment]
What issues are you having with it?

**Comment by DPr00f** [comment]
I'll delete my comment. I thought this was another repo. Sorry
