### ISSUE TITLE
Error: InternalOpenIDError: Failed to verify assertion

### ISSUE THREAD

**Issue by aidenwallis** [liamcurry/passport-steam#27]
Hi,

I'm getting this error and I cannot seem to work out why, I'm using MySQL for my database if that's any use.

> InternalOpenIDError: Failed to verify assertion at /home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/lib/passport-openid/strategy.js:184:36 at /home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:927:12 at /home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:1051:16 at /home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:1169:16 at Request._callback (/home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:190:7) at Request.self.callback (/home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/node_modules/request/request.js:198:22) at emitTwo (events.js:87:13) at Request.emit (events.js:172:7) at Request.<anonymous> (/home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/node_modules/request/request.js:1035:10) at emitOne (events.js:82:20)

**Comment by welps** [comment]
Did you recently run `npm install` or `npm update`? 

Are you perhaps redirecting the `returnURL` that's set within the passport configuration?

**Comment by aidenwallis** [comment]
These were only installed today, so no need to update, I also cleared node-gyp to refresh it all, the returnURL is fine as well, the only thing that redirects is when the authentication is successful.

**Comment by welps** [comment]
`1169:16` from `open-id` is `return callback({ message: 'Invalid signature' }, { authenticated: false });`

Is this running off your home computer? If so, are you using a proxy/firewall?

**Comment by aidenwallis** [comment]
Nope we're running off of an Ubuntu server with an Nginx reverse proxy in front to manage SSL, load-balancing etc.

**Comment by aidenwallis** [comment]
Would it be useful if I attached the executing code where the strategy is configured?

**Comment by welps** [comment]
Yeah, definitely.

**Comment by aidenwallis** [comment]
Here is the code:

`app.enable('trust proxy', 1);
app.use(session({
  proxy: true,
  secret: config.cookies.secret,
  name: config.cookies.key,
  resave: false,
  saveUninitialized: false,
  cookie: {
    httpOnly: true
  } // will be configuring session store later
}));
app.use(function(req, res, next){
  res.locals.currentUrl = '//' + req.hostname + req.url;
  res.locals.date = new Date().getTime();
  res.locals.user = req.user;
  res.locals.usercount = users;
  next();
});
app.use(passport.initialize());
app.use(passport.session());
passport.use(new passportSteam({
    returnURL: 'http://INSERT_IP_HERE/auth/steam/callback',
    apiKey: '' // removed api key,
    realm: 'http://INSERT_IP_HERE',
  }, function(identifier, profile, done){
    var user = {
      identifier: identifier,
      id: identifier.match(/\d+$/)[0],
      profile: profile
    }
    db.query("SELECT * FROM `steam_users` WHERE `steam_id` = ?", [user.id], function(err, res, fields){
      if(res){
        return done(err, user.id);
      } else {
        db.query("INSERT INTO `steam_users` (`steam_id`) VALUES (?)", [user.id], function(err, res, fields){
          return done(err, user.id);
        });
      }
      console.log("err: \n" + err + "\n"); // db debug
      console.log("Res: \n" + res + "\n"); // db debug
      console.log("fields: \n" + fields + "\n"); // db debug
    });
  }
));
passport.serializeUser(function(user, done){
  done(null, user);
});
passport.deserializeUser(function(obj, done){
  done(null, obj);
});
app.use('/auth/steam', passport.authenticate('steam'));
app.use('/auth/steam/callback', passport.authenticate('steam', { failureRedirect: '/auth/failure', successRedirect: '/' }));
`

**Comment by welps** [comment]
Cool. I'm able to reproduce. Let me look into it.

**Comment by aidenwallis** [comment]
Ok thank you! I'm on a deadline for 2 projects with this so thank you very much for the help! To add some more information, I cannot seem to use a database with it, but process.nextTick works, if that may be any use whatsoever, the database definitely works.

**Comment by mnzt** [comment]
Do you mean the database works within `process.nextTick()`? If so, that's correct.

https://nodejs.org/api/process.html#process_process_nexttick_callback_arg

**Comment by welps** [comment]
Hey, so the error you're seeing is kind of unrelated to your issue. For the return route, instead of 
````
app.use('/auth/steam/callback', 
    passport.authenticate('steam', { failureRedirect: '/auth/failure', 
    successRedirect: '/' }));
````
You should use:

````
app.use('/auth/steam/callback',
    passport.authenticate('steam', { failureRedirect: '/' }),
    function(req, res) {
        res.redirect('/'); // or whatever the redirected page should be
    });
````
successRedirect doesn't work for whatever reason (OpenID specific issue probably) which is why you see that error. The method I listed above is the one advocated by the parent dependency `passport-openid` and it works.

FYI, `res` will always be true in the code you gave since node-mysql returns an empty object for a query with no result. `Object.keys(res).length > 0` is likely what you're looking for. Otherwise, the code worked correctly from me trying to reproduce the error.

Let me know if this worked out for you. Thanks.

**Comment by aidenwallis** [comment]
I don't use `process.nextTick()`, I'm saying without a database, I use the callback inside of `process.nextTick()`, which works.

**Comment by welps** [comment]
Hey @aidenwallis, let me know if my solution above worked out for you. Thanks.

**Comment by aidenwallis** [comment]
Sadly it didn't resolve the issue :(

**Comment by welps** [comment]
@aidenwallis , here's the code you gave me that I rolled into an Express barebones project and was able to use successfully: https://github.com/welps/aidenwallis

Can you try downloading it, configuring it, and verify that it works on your end?

**Comment by mnzt** [comment]
@welps were you using NPM3?

NPM version shouldn't be the issue, but I've got a feeling it may.

**Comment by mnzt** [comment]
@welps were you using NPM3?

NPM version shouldn't be the issue, but I've got a feeling it may.

**Comment by welps** [comment]
Yeah, I'm on NPM3. I can see that he's on NPM2 from the stack trace, but I'm not sure how NPM can be a factor since the dependencies were just flattened unless there's a conflict. As far as I can tell, it seems like the user's project is still in its infancy so there shouldn't be a load of dependencies yet.

**Comment by mnzt** [comment]
Just an additional step to debugging. I once experienced issues with NPM2 that were solved by NPM3. 

You stated you're using NGINX infront, and running a reverse proxy back to the application. Try using the FQDN as the realm and return address, not the IP.

**Comment by aidenwallis** [comment]
None of the ideas fixed it, have decided to re-write in PHP for this project. Thank God for being comfortable in multiple languages! :P

**Comment by welps** [comment]
Sorry to hear we couldn't help. I was able to reproduce your issue, remedy it in my dev environment, and repeat it on my staging using the repo I uploaded, so it must be something on your end.

Here's the full debug log from my staging:

`DEBUG=* npm start`

````
 express:application booting in development mode +0ms
  express:application set "view" to [Function: View] +1ms
  express:application set "views" to '/aidenwallis/views' +0ms
  express:application set "jsonp callback name" to 'callback' +1ms
  express:application set "views" to '/aidenwallis/views' +0ms
  express:application set "view engine" to 'jade' +1ms
  express:router use / query +5ms
  express:router:layer new / +0ms
  express:router use / expressInit +1ms
  express:router:layer new / +0ms
  express:router use / logger +1ms
  express:router:layer new / +0ms
  express:router use / jsonParser +28ms
  express:router:layer new / +1ms
  express:router use / urlencodedParser +3ms
  express:router:layer new / +0ms
  express:router use / cookieParser +1ms
  express:router:layer new / +0ms
  express:router use / serveStatic +1ms
  express:router:layer new / +0ms
  express:application set "trust proxy" to true +0ms
  express:application set "trust proxy fn" to [Function] +1ms
  express:router use / session +1ms
  express:router:layer new / +0ms
  express:router use / <anonymous> +0ms
  express:router:layer new / +1ms
  express:router use / initialize +0ms
  express:router:layer new / +0ms
  express:router use / authenticate +2ms
  express:router:layer new / +0ms
  express:router use /auth/steam authenticate +0ms
  express:router:layer new /auth/steam +1ms
  express:router use /auth/steam <anonymous> +0ms
  express:router:layer new /auth/steam +0ms
  express:router use /auth/steam/callback authenticate +0ms
  express:router:layer new /auth/steam/callback +1ms
  express:router use /auth/steam/callback <anonymous> +0ms
  express:router:layer new /auth/steam/callback +0ms
  express:router use / router +0ms
  express:router:layer new / +1ms
  express:router use /users router +0ms
  express:router:layer new /users +0ms
  express:router use / <anonymous> +1ms
  express:router:layer new / +0ms
  express:router use / <anonymous> +0ms
  express:router:layer new / +0ms
  express:router use / <anonymous> +1ms
  express:router:layer new / +0ms
  express:application set "port" to 3000 +1ms
  test:server Listening on port 3000 +12ms
  express:router dispatching GET /auth/steam +6s
  express:router query  : /auth/steam +2ms
  express:router expressInit  : /auth/steam +1ms
  express:router logger  : /auth/steam +1ms
  express:router jsonParser  : /auth/steam +3ms
  body-parser:json skip empty body +0ms
  express:router urlencodedParser  : /auth/steam +0ms
  body-parser:urlencoded skip empty body +1ms
  express:router cookieParser  : /auth/steam +0ms
  express:router serveStatic  : /auth/steam +2ms
  send stat "/aidenwallis/public/auth/steam" +2ms
  express:router session  : /auth/steam +3ms
  express-session fetching 60Nv2Fay9l8rv9O7C5DtheZqHr_3T5Sx +2ms
  express-session no session found +1ms
  express:router <anonymous>  : /auth/steam +3ms
  express:router initialize  : /auth/steam +0ms
  express:router authenticate  : /auth/steam +1ms
  express:router trim prefix (/auth/steam) from url /auth/steam +1ms
  express:router authenticate /auth/steam : /auth/steam +0ms
  morgan log request +168ms
GET /auth/steam 302 181.165 ms - 0
  express:router dispatching GET /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +2s
  express:router query  : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +1ms
  express:router expressInit  : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +4ms
  express:router logger  : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +1ms
  express:router jsonParser  : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +1ms
  body-parser:json skip empty body +0ms
  express:router urlencodedParser  : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +1ms
  body-parser:urlencoded skip empty body +0ms
  express:router cookieParser  : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +0ms
  express:router serveStatic  : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +1ms
  send stat "/aidenwallis/public/auth/steam/callback" +0ms
  express:router session  : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +1ms
  express-session fetching 60Nv2Fay9l8rv9O7C5DtheZqHr_3T5Sx +1ms
  express-session no session found +0ms
  express:router <anonymous>  : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +1ms
  express:router initialize  : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +0ms
  express:router authenticate  : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +1ms
  express:router trim prefix (/auth/steam) from url /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +0ms
  express:router authenticate /auth/steam : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +0ms

MANUAL CONSOLE LOG OF MY STEAMID HERE

  express:router trim prefix (/auth/steam) from url /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +2s
  express:router <anonymous> /auth/steam : /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED +1ms
  express-session saving MYSESSIONIDREMOVED +5ms
  express-session split response +1ms
  express-session set-cookie dsadsa=s%3AMYSESSIONIDREMOVED.DflD7PF4rSUgfJlL8x715mBiR2G%2BPKgJFqAvJmCnhZA; Path=/; HttpOnly +2ms
  morgan log request +2ms
GET /auth/steam/callback?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2FMYSTEAMIDNUMBERREMOVED&openid.return_to=http%3A%2F%2Fdev%3A3000%2Fauth%2Fsteam%2Fcallback&openid.response_nonce=2016-02-04T18%3A25%3A47Zs0z1KBS7GQWAzUCb9NL8P9izDTc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=MYSIGNATUREREMOVED 302 2037.750 ms - 46
  express:router dispatching GET / +9ms
  express:router query  : / +1ms
  express:router expressInit  : / +0ms
  express:router logger  : / +0ms
  express:router jsonParser  : / +1ms
  body-parser:json skip empty body +1ms
  express:router urlencodedParser  : / +2ms
  body-parser:urlencoded skip empty body +1ms
  express:router cookieParser  : / +0ms
  express:router serveStatic  : / +0ms
  send stat "/aidenwallis/public/index.html" +1ms
  express:router session  : / +2ms
  express-session fetching MYSESSIONIDREMOVED +1ms
  express-session session found +0ms
  express:router <anonymous>  : / +1ms
  express:router initialize  : / +0ms
  express:router authenticate  : / +0ms
  express:router router  : / +1ms
  express:router dispatching GET / +0ms
  express:view lookup "index.jade" +471ms
  express:view stat "/aidenwallis/views/index.jade" +4ms
  express:view render "/aidenwallis/views/index.jade" +0ms
  express-session touching +102ms
  express-session touched +1ms
  morgan log request +1ms
GET / 304 588.274 ms - -
  express:router dispatching GET /stylesheets/style.css +104ms
  express:router query  : /stylesheets/style.css +1ms
  express:router expressInit  : /stylesheets/style.css +1ms
  express:router logger  : /stylesheets/style.css +0ms
  express:router jsonParser  : /stylesheets/style.css +2ms
  body-parser:json skip empty body +0ms
  express:router urlencodedParser  : /stylesheets/style.css +0ms
  body-parser:urlencoded skip empty body +0ms
  express:router cookieParser  : /stylesheets/style.css +1ms
  express:router serveStatic  : /stylesheets/style.css +1ms
  send stat "/aidenwallis/public/stylesheets/style.css" +0ms
  send pipe "/aidenwallis/public/stylesheets/style.css" +1ms
  send modified Thu, 04 Feb 2016 18:23:07 GMT +1ms
  send etag W/"6f-152ad860620" +0ms
  send content-type text/css +1ms
  send not modified +1ms
  morgan log request +1ms
GET /stylesheets/style.css 304 7.321 ms - -
````

**Comment by tlenclos** [comment]
I think I have the same issue trying to implement the open-id authentication in feathersJS. It is working with a simple express app but not with feathers middleware... 😞 

https://github.com/feathersjs/feathers-authentication/issues/154
