### ISSUE TITLE
Unknown authentication strategy "steam"

### ISSUE THREAD

**Issue by seanc** [liamcurry/passport-steam#42]
I'm currently receiving this error when I try to visit my steam auth route.

```
Unknown authentication strategy "steam"

Error: Unknown authentication strategy "steam"
    at attempt (/home/sean/projects/{redacted}/node_modules/passport/lib/middleware/authenticate.js:173:37)
    at authenticate (/home/sean/projects/{redacted}/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/home/sean/projects/{redacted}/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/sean/projects/{redacted}/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/sean/projects/{redacted}/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/sean/projects/{redacted}/node_modules/express/lib/router/layer.js:95:5)
    at /home/sean/projects/{redacted}/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/sean/projects/{redacted}/node_modules/express/lib/router/index.js:330:12)
    at next (/home/sean/projects/{redacted}/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/home/sean/projects/{redacted}/node_modules/express/lib/router/index.js:176:3)
    at router (/home/sean/projects/{redacted}/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/home/sean/projects/{redacted}/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/sean/projects/{redacted}/node_modules/express/lib/router/index.js:312:13)
    at /home/sean/projects/{redacted}/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/sean/projects/{redacted}/node_modules/express/lib/router/index.js:330:12)
    at next (/home/sean/projects/{redacted}/node_modules/express/lib/router/index.js:271:10)
```

Here is my code as well.

```javascript
// index.js

var express = require('express');
var router = express.Router();
var passport = require('passport');

router.get('/', function(req, res, next) {
  res.render('index');
});

router.get('/logout', function(req, res) {
  req.logout();
  res.redirect('/');
});

// Steam
router.get('/auth',
  passport.authenticate('steam', {failureRedirect: '/'}),
  function(req, res) {
    res.redirect('/');
  });

router.get('/auth/return',
  passport.authenticate('steam', {failureRedirect: '/'}),
  function(req, res) {
    res.redirect('/');
  });

module.exports = router;
```

```javascript
// app.js

var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var session = require('express-session');
var mongoose = require('mongoose');
var config = require('./config');
var passport = require('passport');
var SteamStrategy = require('passport-steam').Strategy;

mongoose.connect(`mongodb://${config.mongodb.host}/${config.mongodb.database}`);

passport.serializeUser(function(user, done) {
  done(null, user);
});

passport.deserializeUser(function(user, done) {
  done(null, user);
});

console.log(config.steam, SteamStrategy);

passport.use(new SteamStrategy(config.steam), function(id, profile, done) {
  process.nextTick(function() {
    console.log(profile, id);
    profile.id = id;

    return done(null, profile);
  });
});

var routes = require('./routes/index');
var users = require('./routes/users');

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(require('node-sass-middleware')({
  src: path.join(__dirname, 'public'),
  dest: path.join(__dirname, 'public'),
  indentedSyntax: false,
  sourceMap: true
}));
app.use(session(config.session));
app.use(passport.initialize());
app.use(passport.session());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', routes);
app.use('/users', users);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: err
    });
  });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {}
  });
});


module.exports = app;
```

And my package.json dependencies

```json
// package.json
{
  "dependencies": {
    "body-parser": "~1.15.1",
    "cookie-parser": "~1.4.3",
    "debug": "~2.2.0",
    "express": "~4.13.4",
    "express-session": "^1.14.0",
    "jade": "~1.11.0",
    "mongoose": "^4.5.8",
    "morgan": "~1.7.0",
    "node-sass-middleware": "0.8.0",
    "passport": "^0.3.2",
    "passport-steam": "^1.0.5",
    "rc": "^1.1.6",
    "serve-favicon": "~2.3.0"
  }
}
```

**Comment by seanc** [comment]
I realized I didn't pass the strategy name in `passport.use`.

**Comment by OverVlad** [comment]
@seanc i have some issue. How you solve it?
