### ISSUE TITLE
InternalOpenIDError: Failed to verify assertion

### ISSUE THREAD

**Issue by feedarz** [liamcurry/passport-steam#49]
Error that i am getting:
`InternalOpenIDError: Failed to verify assertion
0|gate     |     at /var/apps/node_modules/passport-steam/node_modules/passport-openid-node6support/lib/passport-openid/strategy.js:184:36
0|gate     |     at /var/apps/node_modules/passport-steam/node_modules/passport-openid-node6support/node_modules/openid/openid.js:1020:12
0|gate     |     at /var/apps/node_modules/passport-steam/node_modules/passport-openid-node6support/node_modules/openid/openid.js:1190:16
0|gate     |     at /var/apps/node_modules/passport-steam/node_modules/passport-openid-node6support/node_modules/openid/openid.js:1297:14
0|gate     |     at Request._callback (/var/apps/node_modules/passport-steam/node_modules/passport-openid-node6support/node_modules/openid/openid.js:243:7)
0|gate     |     at self.callback (/var/apps/node_modules/request/request.js:186:22)
0|gate     |     at Request.emit (events.js:107:17)
0|gate     |     at Request.onRequestError (/var/apps/node_modules/request/request.js:845:8)
0|gate     |     at ClientRequest.emit (events.js:107:17)
0|gate     |     at TLSSocket.socketErrorListener (_http_client.js:271:9)`

node -v:
`v0.12.17`

I know my node version is old, but thats cuz i tried different ones to check maybe if its version issue.

passport v0.3.2
passport-openid-node6support v1.0.0
passport-steam v1.0.7
express v4.14.0

My code for authentication and save login data:
```
var app = express();

app.enable('trust proxy', 1);

app.listen(80);

app.set('views', __dirname + '/views');
app.set('view engine', 'ejs');

app.use(session({ proxy: true, secret: CONFIG.express.secret, name: CONFIG.express.name, resave: false, saveUninitialized: false, cookie: { httpOnly: true } }));

app.use(function(req, res, next){
	res.locals.currentUrl = '//' + req.hostname + req.url;
	res.locals.date = new Date().getTime();
	res.locals.user = req.user;
	next();
});

app.use(passport.initialize());
app.use(passport.session());

passport.serializeUser(function(user, done) {
    done(null, user);
});

passport.deserializeUser(function(obj, done) {
    done(null, obj);
});

passport.use(new SteamStrategy({
        returnURL : CONFIG.website+'/auth/steam/return',
        realm : CONFIG.website,
        apiKey : CONFIG.apikey,
		profile : true
    }, function(identifier, profile, done) {
		process.nextTick(function () {
			profile.identifier = identifier;
			return done(null, profile);
		});
        //profile.identifier = identifier;
        //return done(null, profile);
    }
));

app.get('/logout', function(req, res){
	delete network.players[req.user._json.steamid];
    req.logout();
    res.redirect('/');
});

app.get('/auth/steam', passport.authenticate('steam'), function(req, res) {
    //res.redirect('/');
});

function use_orginalurl(req, res, next){
    req.url = req.originalUrl;
    next();
}

app.get('/auth/steam/return', passport.authenticate('steam', { failureRedirect: '/' }), function(req, res) {
    console.log(req.user._json.steamid + ' authenticated');
    network.players[req.user._json.steamid] = { steamid : 0, authenticated : true, id : 0, user : 0, inventory : { items : {} } };
	console.log('authenticated = '+network.authenticated(req.user._json.steamid));
    network.players[req.user._json.steamid].user = req.user._json;
    mysqlConnection.query('SELECT * FROM users WHERE steamid = \''+req.user._json.steamid+'\'', function(err, row, results){
        if(err) {
            if(err.code === 'PROTOCOL_CONNECTION_LOST' || err.code === 'ECONNRESET'){
                handleDisconnect();
            }
            console.log('mysql error: ' + err);
        }
        if(row && row.length > 0){
            console.log('old user');
            mysqlConnection.query('UPDATE users SET name = \''+removescript(removequots(req.user._json.personaname))+'\', img = \''+req.user._json.avatarfull+'\' WHERE steamid =\''+req.user._json.steamid+'\'', function(err, rows, fields) {
                if(err) {
                    console.log('mysql error: ' + err);
                    if(err.code === 'PROTOCOL_CONNECTION_LOST' || err.code === 'ECONNRESET'){
                        handleDisconnect();
                    }
                } else {
                    res.redirect('/');
                }
            });
        } else {
            console.log('new user');
            mysqlConnection.query('INSERT INTO users (`steamid`, `name`, `img`) VALUES (\''+req.user._json.steamid+'\', \''+removescript(removequots(req.user._json.personaname))+'\', \''+req.user._json.avatarfull+'\')', function(err, rows, fields) {
                if(err) {
                    console.log('mysql error: ' + err);
                    if(err.code === 'PROTOCOL_CONNECTION_LOST' || err.code === 'ECONNRESET'){
                        handleDisconnect();
                    }
                } else {
                    res.redirect('/');
                }
            });
        } 
    });
});
```

Please help.

**Comment by feedarz** [comment]
Please, dont redirect me to other simular issues, i ve read all of them, none helped me.

**Comment by feedarz** [comment]
Fixed it.

node -v
`v4.7.0`

passport v0.3.2
passport-openid-node6support v1.0.0 <-- removed it
passport-steam v1.0.7
express v4.14.0

**Comment by FlorianBELLAZOUZ** [comment]
Hi @feedarz ,

I have the same issue on node v6.9.1.
What do you mean by : passport-openid-node6support v1.0.0 <-- removed it

Do you edit the source code ? =)

**Comment by feedarz** [comment]
Kinda. 

If you want it to work properly on node 4.x, you have to go to strategy.js, go to 5 line and change
```JAVASCRIPT
  , OpenIDStrategy = require('passport-openid-node6support').Strategy
```
to
```JAVASCRIPT
  , OpenIDStrategy = require('passport-openid').Strategy
```
Also go to package.json and change dependency on line 35 from
```JAVASCRIPT
    "passport-openid-node6support": "^1.0.0",
```
to
```JAVASCRIPT
    "passport-openid": "^1.0.0",
```
