### ISSUE TITLE
I get an error when authorizing Steam

### ISSUE THREAD

**Issue by Senior22** [liamcurry/passport-steam#59]
```
Failed to verify assertion (message: Invalid signature)
    at /var/apps/node_modules/passport-steam/node_modules/passport-openid/lib/passport-openid/strategy.js:184:36
    at /var/apps/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:981:12
    at /var/apps/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:1105:16
    at /var/apps/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:1223:16
    at Request._callback (/var/apps/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:244:7)
    at Request.self.callback (/var/apps/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/var/apps/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
```

**Comment by Senior22** [comment]
How can I solve this problem?

**Comment by Robinlemon** [comment]
@Senior22 It is likely the package is not updated.

Try `$ npm update`, if this is unsuccessful, update your npm version via `$ npm install -g npm`

**Comment by bdefore** [comment]
I've left an answer here that may help: https://github.com/liamcurry/passport-steam/issues/68#issuecomment-658367752
