### ISSUE TITLE
Cannot read property 'steamid' of undefined

### ISSUE THREAD

**Issue by trzyrazyzero** [liamcurry/passport-steam#62]
Hello,
im getting sometimes this error:
```javascript
[Error] TypeError: Cannot read property 'steamid' of undefined
    at steam.getPlayerSummaries.callback (/home/pr/node_modules/passport-steam/lib/passport-steam/strategy.js:28:39)
    at IncomingMessage.<anonymous> (/home/pr/node_modules/steam-web/lib/steam.js:484:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at IncomingMessage.EventEmitter.emit (/home/pr/node_modules/sc-domain/index.js:12:31)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Its related to this function https://github.com/liamcurry/passport-steam/blob/master/lib/passport-steam/strategy.js#L15-L42

Any fix?

**Comment by Robinlemon** [comment]
@trzyrazyzero Either your APIKey is wrong, or you're spamming the endpoint too much so they have temporarily blocked you.

1) Verify your APIKey with what you registered on Steam.
2) Wait a few hours (potentially days if you spam lots) and try again.
