### ISSUE TITLE
Cannot read property 'steamid' of undefined

### ISSUE THREAD

**Issue by paralin** [liamcurry/passport-steam#9]
```
/node_modules/passport-steam/lib/passport-steam/strategy.js:58
            id: result.response.players[0].steamid,
                                          ^
TypeError: Cannot read property 'steamid' of undefined
    at steam.getPlayerSummaries.callback (/node_modules/passport-steam/lib/passport-steam/strategy.js:58:43)
    at IncomingMessage.<anonymous> (/node_modules/passport-steam/node_modules/steam-web/lib/steam.js:218:7)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by phiresky** [comment]
This does seem to be an issue in the library, not in the user's callbacks
